### ISSUE TITLE
ellipse fits for barred galaxies

### ISSUE THREAD

**Issue by MukundanK** [astropy/photutils#1016]
my aim is to fit ellipses to barred galaxies and use the change in ellipticity to identify bars/ quantify bar length in galaxies. I understand that the ellipse fit algorithm is primarily meant for smooth elliptical light distributions. 
A simple ellipse fit with sigma clipping (done according to the examples on photutils-notebooks) gives me the following result:
![plots](https://user-images.githubusercontent.com/55205838/73156672-2357eb00-40a4-11ea-9cbb-a1dd4f1f37ea.jpg)
![residual](https://user-images.githubusercontent.com/55205838/73156675-2521ae80-40a4-11ea-961f-8dcdfca3c050.jpg)
I want to perform this fit on several images, so, I do not want to perform it manually. How can I obtain better fits for barred galaxies? 

Many others have fits in which the ellipses do not converge. Like these for example:
<img width="481" alt="Screen Shot 2020-01-27 at 1 37 05 AM" src="https://user-images.githubusercontent.com/55205838/73157081-91e97880-40a5-11ea-8fd3-d16f1e10817e.png">
<img width="258" alt="Screen Shot 2020-01-27 at 1 36 10 AM" src="https://user-images.githubusercontent.com/55205838/73157082-93b33c00-40a5-11ea-94b4-f592e4e02978.png">

Any suggestions on how to obtain better fits would be very helpful.

**Comment by larrybradley** [comment]
@ibusko Do you have any suggestions?

**Comment by ibusko** [comment]
@larrybradley, I have no simple solution out of the top of my head. Problems like this one are complex and require some trial-and-error with the fit parameters in order to just get a grasp on what is going on. My suggestion would be to try different sampling methods, different ellipse geometry fit parameters (such as the step), and different stopping criteria, to see if it improves anything. 

Unfortunately I am leaving on vacation tomorrow and will be back only on Feb 18. I will be happy to look more in depth in this issue then.

**Comment by larrybradley** [comment]
Thanks, @ibusko.

**Comment by MukundanK** [comment]
Thanks, @ibusko. I will try to play around with more parameters to see if I can improve the fit.

**Comment by larrybradley** [comment]
Thanks, @MukundanK.
