### ISSUE TITLE
question about code update

### ISSUE THREAD

**Issue by Timmy217** [astropy/photutils#1048]
At first, my photutils' version was 0.7.1 and I uninstalled it and reinstall 0.7.2 version, but when I import photutils, it is still 0.7.1, how to figure?

**Comment by larrybradley** [comment]
You can update the version without uninstalling.  Using pip:  `pip install --upgrade photutils`. For conda:  `conda update photutils`.

**Comment by bijusaha-astro** [comment]
Hello, 

I had Photutils version 0.4 (as I figured out using the command photutils.test(), assuming this is the correct method). I have attached a screenshot of the output, which mentions that photutils version in 0.4. In order to resolve the "radial gradient computation" error,
![Screenshot from 2023-10-08 12-05-47](https://github.com/astropy/photutils/assets/101668391/3288e78d-1b5d-4783-9b14-01e7fd5a76b5)
 mentioned in one of the earlier issues, I want to switch to 0.7 or later versions. I employed the above mentioned upgrade commands and then ran the photutils.test(), which still shows the same 0.4 version (refer to the same screenshot). 

How do I understand if at all, my photutils was upgraded? If not, how do I upgrade it to later versions?
