### ISSUE TITLE
Semi-major axis becomes semi-minor axis in photutils.isophote.Ellipse.fit_isophote

### ISSUE THREAD

**Issue by jusneuma** [astropy/photutils#1069]
I am trying to fit ellipses to galaxies at the 25th magnitude. My approach is to first use photutils.isophote.Ellipse.fit_image function to determine the semi-major axis (sma) length at which the galaxy reaches the 25th magnitude (I will call it r25). Afterwards, I fit a single ellipse at the previously determined sma using photutils.isophote.Ellipse.fit_isophote(sma=r25).

Unfortunately the function returns an ellipse with sma=r25, where r25 is actually the semi **minor** axis and the other axis of the ellipse is longer.

Example result: isophote.sma=20 px, isophote.eps = 0.5
I would expect that the other axis is 10 px, but actually it is 40 px!

Thanks for any help!

**Comment by ibusko** [comment]
I'm looking into this now.

**Comment by jusneuma** [comment]
Thank you for looking into this.
In the following, I provide you with the important lines in my code to understand how it works.
I first fit the data (an input .fits image) with a predefined initial geometry with the fit_image function. Then, I interpolate the SMA of the 25th magnitude, i.e. here called f(25). Then, I take the closest isophote of the isolist as input to fit a single isophote at f(25) with the fit_isophote function.
```
from photutils.isophote import Ellipse
from scipy.interpolate import interp1d

ellipse = Ellipse(data, geometry)
isolist = ellipse.fit_image()

EXPTIME = hdu[0].header['exptime']
smalist= isolist.sma
intens=isolist.intens
mag=-2.5*np.log10(intens/(0.25**2))+25+2.5*np.log10(EXPTIME) 
f = interp1d(mag,smalist)

iso = isolist.get_closest(f(25))
geometry = EllipseGeometry(x0=iso.x0, y0=iso.y0, sma=f(25), eps=iso.eps, pa=iso.pa)
ellipse = Ellipse(data, geometry)
isophote = ellipse.fit_isophote(sma=f(25))

```
I will have to check whether I can share the input data here, but in the meantime I attach a plot to visualise one of the extreme cases. Shown in white are the isophotal fits from fit_image and in green the isophote from fit_isophote. You can see the output SMA is 124.7 px and the PA = 46.2 deg. But this is in fact the semi-**minor** axis of the green ellipse.

![Figure_1](https://user-images.githubusercontent.com/57446348/92766093-d2c0a400-f38d-11ea-8e0d-4e4e88c8b4f1.png)

**Comment by jusneuma** [comment]
Just to add: I realise that this might be an extreme case that is difficult to fit, but nevertheless, the SMA given to fit_isophote should be the longest axis of the fitted ellipse, which is not the case here.

**Comment by ibusko** [comment]
Thanks for sharing the code and the picture. Looking at the overlaid ellipses in the picture, it looks like, at the region around `sma=125`, there is a jump on the ellipses orientation. It occurred to me that there is a fundamental difference in the way the `fit_image` and `fit_isophote` methods work. `fit_isophote` is called from within `fit_image` in a loop over successive values of `sma`. In this loop, at every call, the parameters fed into `fit_isophote` change at each iteration. It uses the values obtained at the immediately past iteration, or otherwise adopts values based on certain criteria. That is, even if `fit_image` gave you a result close to what you expected, `fit_isophote` may give a different result, since it was initialized in a different way. Especially in regions with instabilities, such as it seems to be the case at `sma=125`. 

You might want to try to use `fit_image` again at your second step. You may define a small set of `sma` values (using `sma0`, `step`, and min and max `sma`) such that your `r25` value is hit head on. This will provide the algorithm with data taken from the immediate previous fit steps. I am not sure this will work, but I would try it just to see if it makes a difference.

**Comment by jusneuma** [comment]
That solved my problem! I appreciate the help!

As what the fit_isophote function is concerned, I still think that this is a strange behaviour. I'm not worried about a non-accurate fit, I am more puzzled about the fact that the ellipse that I showed in the plot was given with the parameters sma=124.7, eps=0.36, pa 46.2 deg, while it should be sma=124.7/(1-0.36)=194.8, eps=0.36, pa=46.2+90=136.2 deg.

Or, as I said in the title, the semi-major axis became, in fact, the semi-minor axis.

Thank you anyway for the immediate and helpful answer to my specific problem!

**Comment by ibusko** [comment]
I am glad it worked for you!

As for the "flip" in the ellipse orientation, indeed, the algorithm does not check for the case when the semi-minor axis becomes eventually larger than the semi-major axis. The reason is that the semi-major axis is not a fitted parameter, and cannot change by design. All the algorithm can do is to calculate the other axis in a way that minimizes the residuals. 

We could in principle apply a correction to the result, after the algorithm converged. That is, if the resulting ellipse is turned 90 degrees off, as in your example, we could correct it by re-calculating the geometry parameters in the right way. I don't think that a correction like that should be applied by the algorithm itself, though. There are cases where the ellipses *do* turn away from each other in weird ways. All depends on the particular science. 

Please let me know in case you see a way to improve on this. Or on any other matter by the way.
