### ISSUE TITLE
Test failures with scipy 1.6.0

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#1136]
CI tests started failing with the upgrade of scipy from 1.5.4 to 1.6.0.  I've also verified this locally.  The differences appear to mainly be numeric precision differences, but I need to investigate further.

**Comment by prajwel** [comment]
I was wondering why my source deblending script was giving a slightly different number of deblended sources in two different machines with the same Photutils version (1.1.0). I think the Background2D function was affected due to one of the systems having an older Scipy version and this ultimately affected how sources were detected and therefore deblended. After updating Scipy, things are fine. I hope that someone else having the same problem finds this useful.
