### ISSUE TITLE
[v1.1.0] data_properties() fails on scalar background 

### ISSUE THREAD

**Issue by edose** [astropy/photutils#1194]
Scalar backgrounds fail in data_properties() v.1.1.0, but allowed by 1.1.0 documentation. Scalars worked fine in v.1.0.2. Probably, the new error is in the SourceCatalog constructor, possibly in a too-aggressive validation method SourceCatalog._validate_array(self, array, name).

Demo:
data_array = numpy.array([1.0, 2.0])
data_properties(data=data_array, mask=None, background=[1.0,1.0])  # an array background succeeds.
data_properties(data=data_array, mask=None, background=None)  # None background succeeds.
data_properties(data=data_array, mask=None, background=1.0)  # scalar background incorrectly throws exception: "{ValueError}error and background must have the same shape."

Workaround (and possible library fix) is to replace scalar background with numpy.full_like(data_array, background_scalar_value), though allowing a scalar directly would probably be faster in numpy.

Thank you, 
Eric Dose

**Comment by larrybradley** [comment]
@edose Thanks for reporting this.  The `background` keyword is used only to provide statistics of the background image over the array (e.g., its mean, sum, etc.).  The input `data` array should already be background-subtracted.  To compute the background statistics, a 2D image is needed and thus the deprecated `SourceProperties` code would internally convert a scalar background to a 2D background image (`background = np.zeros(data.shape) + background`).

The behavior change in `data_properties` was an unintended consequence of  changing it use the new `SourceCatalog` class.  In the short term I will restore allowing scalar `background` inputs, but I will likely deprecate that because internally all it's doing is creating a 2D array from the scalar.

**Comment by edose** [comment]
Sounds fine. My `data` arrays are already background subtracted, using a scalar from astropy.stats.sigma_clipped_stats(), which I'd expect is a pretty common use case providing a scalar background value, I expect. Such users will need to be sure to make their own size-matched background array when calling data_properties(). The full_like() workaround I mentioned does work well for that.

Thanks.
