### ISSUE TITLE
I want to fix all three parameters, {center, ellipticity, pa} in isophote analysis... how to do that...?

### ISSUE THREAD

**Issue by pinsongzhao** [astropy/photutils#1222]
I want to do isophote analysis for galaxies, and I really want to fix all three geometry parameters {center, eps, pa} at each SMA.
I try to use ellipse.fit_image(), by applying 'fix_center&fix_eps&fix_pa = True'，
but I get one warning and the code returns nothing.
Is it possible to achieve this goal by using Photutils?
Or is there any other function in Photutils can do this?

**Comment by larrybradley** [comment]
@ibusko - is this possible?

**Comment by ibusko** [comment]
@pinsongzhao unfortunately, the behavior you observed is correct. Setting all parameters to fixed prevents the fitting algorithm to calculate everything it needs to look for a solution. 

What you need instead is a way to just sample the image at the ellipse you pre-defined with the geometry parameters. In the `isophote_example1.ipynb` notebook (cell #9) you can see an example of fitting based on an explicit use of the `EllipseSample` class.

You can modify this example by defining a geometry instance with all parameters fixed:

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/3577145/126384385-bd9bab8f-36a9-478b-8310-e15b5e38a778.png">

Even though it reports that 2 iterations were performed, that's actually an artifact (or bug) of the counter that keeps track of the number of iterations. In fact, only one sampling was performed. You can execute that sequence within a loop in `sma` so as to cover the range in semi-major axis length you need.

**Comment by larrybradley** [comment]
Thanks, @ibusko.  @pinsongzhao Here is the link to the notebook:  https://github.com/astropy/photutils-datasets/blob/main/notebooks/isophote/isophote_example1.ipynb

**Comment by pinsongzhao** [comment]
@ibusko ,@larrybradley  Thanks for your help!
I test this method on one model image, all three geometry parameters are fixed.
![Screenshot from 2021-07-21 15-36-29](https://user-images.githubusercontent.com/46621388/126450064-20bd6df2-6086-40b5-bc6f-b33493841b42.png)
but I meet a new problems below. 
 ![Screenshot from 2021-07-21 15-36-29](https://user-images.githubusercontent.com/46621388/126450575-35a3ffba-5c95-4038-9045-b9dc84c4f7a0.png)
when input with a sequence of sma values, it seems that this function would go into an error if the sma go further out.
Is there any methods I could fix this problem?
I really appreciate your patience and look forward to your reply.

**Comment by pinsongzhao** [comment]
@ibusko ,@larrybradley  Thanks for your help!
I test this method on one model image, all three geometry parameters are fixed.
![Screenshot from 2021-07-21 15-36-29](https://user-images.githubusercontent.com/46621388/126450064-20bd6df2-6086-40b5-bc6f-b33493841b42.png)
but I meet a new problems below. 
 ![Screenshot from 2021-07-21 15-36-29](https://user-images.githubusercontent.com/46621388/126450575-35a3ffba-5c95-4038-9045-b9dc84c4f7a0.png)
when input with a sequence of sma values, it seems that this function would go into an error if the sma go further out.
Is there any methods I could fix this problem?
I really appreciate your patience and look forward to your reply.

**Comment by pinsongzhao** [comment]
@ibusko ,@larrybradley  Thanks for your help!
I test this method on one model image, all three geometry parameters are fixed.

![Screenshot from 2021-07-21 15-36-29](https://user-images.githubusercontent.com/46621388/126450064-20bd6df2-6086-40b5-bc6f-b33493841b42.png)

but I meet a new problems below. 
![Screenshot from 2021-07-21 15-39-15](https://user-images.githubusercontent.com/46621388/126452351-239ac20f-1d78-4bcd-a8d2-88024358724c.png)

when input with a sequence of sma values, it seems that this function would go into an error if the sma go further out.
Is there any methods I could fix this problem?
I really appreciate your patience and look forward to your reply.

**Comment by ibusko** [comment]
@pinsongzhao could you please send me the notebook where your test is? I would like to be able to reproduce exactly what you see.

**Comment by pinsongzhao** [comment]
@ibusko, yes, 
here it is [https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel.ipynb](url)
Thank you for your time!

**Comment by pinsongzhao** [comment]
Sorry @ibusko , I just notice the previous link doesn't work, I update the link. 
[https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel.ipynb](https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel.ipynb)

**Comment by ibusko** [comment]
Thanks for providing the code. Sorry, I gave you the wrong solution. It doesn't make sense to call a Fitter object when we are not performing any fit. The Fitter eventually goes bonkers. The correct way to do this is to call the`update()` method in the `EllipseSample` instance. This will extract whatever can be extracted from the image, and stop right there. Not fit is performed.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/3577145/126789019-872ef0a6-7709-406a-98b4-6ca8b4864bed.png">

You can see the available attributes of the sampler instance, here: https://photutils.readthedocs.io/en/stable/api/photutils.isophote.EllipseSample.html#photutils.isophote.EllipseSample

**Comment by pinsongzhao** [comment]
Thank you for your reply, this method do solve my problems! I just have two more questions, I hope to get professional answer/suggestions from you. 
1) Here is my new test code.
[https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel2.ipynb](https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel2.ipynb)  
What I am doing here is to run a test on IRAC-ch1 PSF-image using 'sample.update()', as you can see, all geometry parameters are fixed. I also try 'EllipseFitter.fit()', with center&eps fixed, eps=0.001, release pa (I assume this eps to be very close to a circle and pa will not matter too much). Do you know why 'update()' method would output quite different results from another one? When I directly check the PSF-image, it seems to me the results from 'update()' is not correct (1e-4 at SMA= 20 pix seems too large to me). Does this mean 'fitting' process is important and necessary for some cases? Does no-fit mean large errors?
2) I find that when I use 'sample.update()' method, the output do not provide an error related to the mean value, do you have any suggestions on getting errors here?

Thank you for your time!

**Comment by ibusko** [comment]
Hi,

I adapted your example notebook into this one: https://github.com/ibusko/tests/blob/master/Untitled1.ipynb

It looked to me that the image you used is not well modeled by circular isophotes. They look more triangular than circular. So I tried in my notebook to use a Gaussian2D similar to the one you used in your first notebook, but with circular geometry. And in this case we see better agreement in between the two curves.

I suspect that, because of the non-circularity of the isophotes in your test image, the fitting algorithm tries hard to change the ellipticity and eventually is driven to sample at ellipticities that are far from the almost circular one used as first guess. You can see that by printing the fitted isophotes (use print(isolist1.to_table()) at every step of the loop).

Another problem with this setup is that you are starting the fits at a very small sma, where sampling errors are at a maximum. As the sma is increased, errors in the fit get propagated into the initial (guess) values of the next isophote. One way to improve this is to start from the outside and decrease sma. The problem then is that small SNR in the outskirts of the image will also generate large errors. That’s why the fit_image() method starts with a mid-way sma, increases it to the outside, and then reverses sense and decreases it going to the center of the galaxy.

Ivo



On Jul 26, 2021, at 9:05 AM, pinsongzhao ***@***.******@***.***>> wrote:



Thank you for your reply, this method do solve my problems! I just have two more questions, I hope to get professional answer/suggestions from you.

  1.  Here is my new test code.
https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel2.ipynb<https://urldefense.com/v3/__https://github.com/pinsongzhao/TestPhotutils/blob/main/Testmodel2.ipynb__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!iZmVtHX8gsoaSPeskVtv6uOH0iasTVgRKgirVJWklaGHRAtE1Z9kCIZvfdZdOlM$>
What I am doing here is to run a test on IRAC-ch1 PSF-image using 'sample.update()', as you can see, all geometry parameters are fixed. I also try 'EllipseFitter.fit()', with center&eps fixed, eps=0.001, release pa (I assume this eps to be very close to a circle and pa will not matter too much). Do you know why 'update()' method would output quite different results from another one? When I directly check the PSF-image, it seems to me the results from 'update()' is not correct (1e-4 at SMA= 20 pix seems too large to me). Does this mean 'fitting' process is important and necessary for some cases? Does no-fit mean large errors?
  2.  I find that when I use 'sample.update()' method, the output do not provide an error related to the mean value, do you have any suggestions on getting errors here?

Thank you for your time!

**Comment by pinsongzhao** [comment]
Yes, this results agree well. Thanks very much for your help!
