### ISSUE TITLE
ApertureStats: Curve of Growth support

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1337]
Any plans to implement functionality for curve of growth here? Or at least support single aperture object with one center but an array of radii?

Maybe it is already there but I cannot find it. Any help would be appreciated, @larrybradley . Thanks!

**Comment by larrybradley** [comment]
A curve of growth is pretty easy to calculate (especially now with `ApertureStats`).  It's really just 1 line code to compute the fluxes. Simple example:

```python
import matplotlib.pyplot as plt
from photutils.aperture import ApertureStats, CircularAperture

data = np.ones((101, 101))
radii = np.linspace(1, 40)
fluxes = [ApertureStats(data, CircularAperture((50, 50), r)).sum for r in radii]
plt.plot(radii, fluxes)
```

Support for array of radii or other shape parameters is not forthcoming.  It was discussed at length many years ago and it was decided to not implement.  It leads to a confusing API. 
 since we have things like rotated elliptical annulus apertures that have 5 shape parameters in addition to the position parameter.  The `regions` package went one step further in the other direction and allows only scalar position and shape parameters.

**Comment by pllim** [comment]
Yeah, I ended up implementing something like your suggestion.

If performance is an issue, we'll have to think about how to vectorize this.
