### ISSUE TITLE
photutils.detection.find_peaks returns integers.

### ISSUE THREAD

**Issue by RuiningZHAO** [astropy/photutils#1492]
A bug: `x_peak` and `y_peak` columns returned by `photutils.detection.find_peaks` are of type int.

In function `photutils.detection.peakfinder.find_peaks`, `table` first get the two columns from maximum finding, which may be the cause of this bug.

```
photutils==1.6.0
```

**Comment by larrybradley** [comment]
@RuiningZHAO This is by design.  See the documentation here:  https://photutils.readthedocs.io/en/latest/detection.html#local-peak-detection

"By default, the returned pixel coordinates are always integer-valued (i.e., no centroiding is performed, only the peak pixel is identified). However, a centroiding function can be input via the centroid_func keyword to [find_peaks()](https://photutils.readthedocs.io/en/latest/api/photutils.detection.find_peaks.html#photutils.detection.find_peaks) to compute centroid coordinates with subpixel precision."

`find_peaks` performs a maximum filter over the input `box_size` or `footprint`.  By default, it returns the index of the maximum pixel value.  If you want sub-pixel positions, you need to input a centroiding function into the `centroid_func` keyword.

**Comment by RuiningZHAO** [comment]
Yes, I read about that in the documentation. But it still returns integers even if I specify a centroiding function.

**Comment by RuiningZHAO** [comment]
Ah, I see. I should use `x_centroid` instead of `x_peak`. I didn't notice that. Sorry.
