### ISSUE TITLE
object finding with local peaks

### ISSUE THREAD

**Issue by weiguangcui** [astropy/photutils#1502]
This is more like a question or feature request if this is not possible.
My data array is more like a dark matter density map, with a dominant central object and all the other objects like subhalos inside a halo, which sit in the local density peak. Therefore, I have no problem identifying them with `find_peaks`, see the image in this [link.](https://drive.google.com/file/d/1GQh0bn1cSKkG2TqQoHqP-Dsjj9Om5kpX/view?usp=share_link) However, it is very hard to use `SourceFinder` to identify these objects. I can only manage to remove the central object as background and identify these objects lying at local density peaks. Any suggestions or possible ways to directly identify them? I know Photutils is not designed for this but appreciate any comments.
Many thanks.

Best,
Weiguang

**Comment by larrybradley** [comment]
The `SourceFinder` detects sources above a threshold, which can be input as a 2D ndarray.  So instead of subtracting a model of the central object, you could try using that model as a starting point for defining a 2D threshold image (e.g., your central object model + local threshold).  But I would guess that would give similar results.  In any case, you would need to model the central object because its pixel values are influencing the values of the subhalos.  I don't see how to get around that.

**Comment by weiguangcui** [comment]
Dear Larry,

Many thanks for the suggestion. By the way, how can I provide a model for
background subtraction?

Best,
Weiguang

send through my phone

**Comment by larrybradley** [comment]
To first order, it appears you may be able to fit the central source as an elliptical 2D Gaussian or perhaps a 2D Sersic profile.  Here are the astropy models:

- https://docs.astropy.org/en/stable/api/astropy.modeling.functional_models.Gaussian2D.html#astropy.modeling.functional_models.Gaussian2D

- https://docs.astropy.org/en/stable/api/astropy.modeling.functional_models.Sersic2D.html
