### ISSUE TITLE
Problem with 3D inputs to GriddedPSFModel

### ISSUE THREAD

**Issue by keflavich** [astropy/photutils#1660]
The behavior of `grid.evaluate` changed with this commit:

https://github.com/astropy/photutils/commit/0198872afab9135fae5b2048735c4b86cd2a6400

MWE:
```python
import os.path as op
from itertools import product

import numpy as np
import pytest
from astropy.modeling.models import Gaussian2D
from astropy.nddata import NDData
from numpy.testing import assert_allclose

from photutils.psf import GriddedPSFModel
from photutils.segmentation import SourceCatalog, detect_sources
from photutils.utils._optional_deps import HAS_MATPLOTLIB, HAS_SCIPY
psfs = []
y, x = np.mgrid[0:101, 0:101]
for i in range(16):
    theta = i * 10.0 * np.pi / 180.0
    g = Gaussian2D(1, 50, 50, 10, 5, theta=theta)
    m = g(x, y)
    psfs.append(m)

xgrid = [0, 40, 160, 200]
ygrid = [0, 60, 140, 200]
grid_xypos = list(product(xgrid, ygrid))

meta = {}
meta['grid_xypos'] = grid_xypos
meta['oversampling'] = 4

nddata = NDData(psfs, meta=meta)
grid = psfmodel = GriddedPSFModel(nddata)

stampsz = 5
col = [0, 1000, 5000]
row = [1000, 0, 5000]
rows, cols = np.indices((stampsz, stampsz)) - (np.array([stampsz, stampsz])-1)[:, None, None] / 2.

col = np.atleast_1d(col)
row = np.atleast_1d(row)
rows = rows[:, :, None] + row[None, None, :]
cols = cols[:, :, None] + col[None, None, :]

for ii in range(3):
    pl.subplot(1, 3, ii+1)
    pl.imshow(grid.evaluate(cols, rows, 1, col, row)[:,:,ii])
```

Old (correct) behavior:
![image](https://github.com/astropy/photutils/assets/143715/e2f005f1-3003-4abd-bd7e-e9af46deb29b)

New (incorrect) behavior:
![image](https://github.com/astropy/photutils/assets/143715/5212d069-c061-421f-b3c3-696cd35b5dc0)

Without digging deeply, I think the cached interpolator has a fixed centerpoint, while it's supposed to change.

**Comment by larrybradley** [comment]
@keflavich Actually, this is not a regression because `GriddedPSFModel` has **never** worked correctly with 3D inputs (going back to when it was first introduced).  The model caching is a red herring.  The model evaluation never supported the 3D broadcasting that you are using (the PSF photmetry classes only use 2D inputs -- which work correctly).  Your "Old" behavior is wrong too.  The output you are expecting should have 3 different images instead of all the same image.  This would be the correct output:
![epsf_grid_example](https://github.com/astropy/photutils/assets/4992897/cc4ec430-28ab-4620-831c-37275a0934af)

For your "Old" behavior, all three images are the same because a given `GridedPSFModel` can only have one `x_0, y_0` position.  Internally, the code uses only `col[0], row[0]` as the position.  Your "New" behavior is actually internally consistent given that assumption, and it's the exact behavior when `GriddedPSFModel` was first added.  At some point it changed to return your "Old" behavior, and then finally it changed back the "New" (more-consistent) behavior back in 
https://github.com/astropy/photutils/pull/1503.

I will look into allowing 3D inputs.  The PSF photometry code and related tools use 2D inputs and work correctly.  This is not likely a common use case.  How are you using the 3D inputs?  Is it to create simulated images?

**Comment by keflavich** [comment]
Ah, thanks!  This makes sense, and it's good to know the behavior I was relying on was both incorrect and temporarily introduced.

I'm... not actually sure the 3d inputs are necessary.  What I really need is the PSF evaluated at N different positions, which required the 3d input to get the desired 3d output, but I think now you're highlighting that I simply misunderstood what was going on, and the appropriate way is either a dumb loop over flat inputs or a different 3D input.  I'll investigate a bit further.
