### ISSUE TITLE
returned table columns are incorrect

### ISSUE THREAD

**Issue by astrojohnlewis** [astropy/photutils#233]
when plotting the table returned by aperture_photometry, the x and y columns seem flipped.
I have to use
```python
# Display apertures over image
import matplotlib.pylab as plt
plt.imshow(file,cmap='gray_r')
plt.plot(tab['ycenter'],tab['xcenter'],'o',mfc='None',mec='b')
plt.xlim(0,file.shape[1])
plt.ylim(0,file.shape[0])
plt.show()
```
to display the images, where file contains the image and tab is the returned photometry table

**Comment by cdeil** [comment]
The [getting started example](http://photutils.readthedocs.org/en/latest/photutils/getting_started.html) shows that at least internally to `photutils` it follows our [coordinate convention](http://photutils.readthedocs.org/en/latest/photutils/overview.html#coordinate-conventions) and gives correct results.

Can you try to create a self-contained example we can run?
Then it'll be clear if there's a bug or just a mis-understanding about what `x` and `y` is.

**Comment by astrojohnlewis** [comment]
[This](https://github.com/astrojohnlewis/JJPHATS/blob/master/Photometry.py) shows the code I am using to semi-automate my photometry. 
[Here](http://nbviewer.ipython.org/gist/astrojohnlewis/63bf3ede2a669f5fc865) is an IPython notebook showing the implementation of the program.

**Comment by larrybradley** [comment]
@astrojohnlewis, thanks for your scripts.  `find_peaks()` returns a `Nx2` array of coordinates in `(y, x)` order (see http://photutils.readthedocs.org/en/latest/api/photutils.detection.find_peaks.html#photutils.detection.find_peaks).  You then use the returned `(y, x)` coordinates as input to `CircularAperture`, which requires coordinates to be in `(x, y)` order.  Thus, you need to change line 35:
https://github.com/astrojohnlewis/JJPHATS/blob/master/Photometry.py#L35
of your code to this:
```
apertures = photutils.CircularAperture(np.fliplr(coords), r = ap)
```

**Comment by astrojohnlewis** [comment]
Thanks!

**Comment by cdeil** [comment]
I presume the positions are returned as `(y, x)` because that's what [skimage.feature.peak_local_max](http://scikit-image.org/docs/dev/api/skimage.feature.html#peak-local-max) does and they do it because that can be used directly to index into numpy arrays?

What do you think about returning an `astropy.table.Table` instead with `x` and `y` columns and providing a separate `lookup_image_values` function?
Maybe that would lead to easier-to-read and less error-prone code for astronomers (most of which are not very familiar with the numpy axis order ... even I have to think about it every time or try it out on an example to get it right)?

**Comment by larrybradley** [comment]
@cdeil Yes, I will change it to return a `Table` to make it fool proof.  I understand why it's used, but the numpy axis order is a bit unfortunate.  `photutils` functions use `(x, y)` input, but direct array access uses `(y, x)`.  So the general question becomes what order should functions return?  A `Table` will make this unambiguous.

**Comment by larrybradley** [comment]
`find_peaks()` now returns a `Table` (#240).
