### ISSUE TITLE
Masks created with geometry routines are sometimes not normalized

### ISSUE THREAD

**Issue by tepickering** [astropy/photutils#265]
I'm working on incorporating the ``photutils.geometry`` routines into my code for creating weight matrices.  The routine ``circular_overlap_region`` works fine (i.e. maximum value is 1.0) for both exact and sampled cases.  In the case of ``elliptical_overlap_region``, it works properly when ``exact=1``, but is not properly normalized in the sampled case. ``rectangular_overlap_region`` is likewise not normalized and doesn't yet support the exact case.  Below is a screen snippet showing the difference between the circular and rectangular cases:

![screenshot 2015-04-29 15 20 10](https://cloud.githubusercontent.com/assets/2481822/7399553/ab6d30d0-ee84-11e4-8786-61b82846ad3a.png)

**Comment by larrybradley** [comment]
@tepickering The maximum in the aperture mask won't always be 1.0 because the aperture can be smaller than a pixel (e.g. in your `rectangular_overlap_grid` example, the size is 0.3 x 2 pixels).  If you change your `circular_overlap_grid` example to use the exact method, then it's max shouldn't be 1.0 either (it should be `np.pi * 0.45**2 = 0.6361725`).

However, I don't think the maximum should ever be *more* than 1.0.  @astrofrog?
You may have found a corner case in `rectangular_overlap_grid`.  Can you please send the parameter values that you used (the values of `t['x_min']`, `...`, `ang`) so I can investigate further?  Thanks!

**Comment by tepickering** [comment]
sorry, here's the same calculation with the actual numbers filled in:

![screenshot 2015-04-30 10 55 37](https://cloud.githubusercontent.com/assets/2481822/7415532/9feebb9a-ef27-11e4-9b8e-aa76bf2c5003.png)

you're right that the max will be less than one in cases where the aperture is small (e.g. radius < pixel width).  in this case, there are pixels fully contained within the apertures and those are given values of 1.0 in the circular case and 85.7338820302 in the rectangular one.
