### ISSUE TITLE
photutils.test() error

### ISSUE THREAD

**Issue by zouhu** [astropy/photutils#266]
when running the test, it give the errors as below:

        # check that array contains numbers or long int objects
        if (value.dtype.kind in 'OSU' and
            not (value.dtype.kind == 'O' and
                 isinstance(value.item(() if value.ndim == 0 else 0),
                            numbers.Number))):
>           raise TypeError("The value must be a valid Python or "
                            "Numpy numeric type.")
E           TypeError: The value must be a valid Python or Numpy numeric type.

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/astropy/units/quantity.py:243: TypeError
Some tests are known to fail when run from the IPython prompt; especially, but not limited to tests involving logging and warning handling.  Unless you are certain as to the cause of the failure, please check that the failure occurs outside IPython as well.  See http://docs.astropy.org/en/stable/known_issues.html#failing-logging-tests-when-running-the-tests-in-ipython for more information.
============== 12 failed, 316 passed, 78 skipped in 8.64 seconds ==============

**Comment by larrybradley** [comment]
Thanks, @zouhu.  This issue was fixed in https://github.com/astropy/photutils/issues/228.  It only affects `photutils 0.1` in the very specific case of performing aperture photometry with an `astropy.nddata.NDData` object that has `astropy` units.  If you need that specific functionality, then please use the current development version until `0.2` is released.
