### ISSUE TITLE
Mask function causes crash in aperture_photometry

### ISSUE THREAD

**Issue by StarryNate** [astropy/photutils#267]
Hello,

My system is running Fedora 21 x86_64.
I'm trying to use aperture photometry with a bad-pixel mask. When I call aperture_photometry and pass it a mask, I get the following error:

/usr/lib64/python2.7/site-packages/photutils/aperture_core.pyc in aperture_photometry(data, apertures, unit, wcs, error, effective_gain, mask, method, subpixels, pixelwise_error)
   1320         # to the aperture sums
   1321         data = copy.deepcopy(data)    # do not modify input data
-> 1322         data *= ~mask
   1323 
   1324     # Check whether we really need to calculate pixelwise errors, even if

/usr/lib64/python2.7/site-packages/astropy/units/quantity.pyc in __imul__(self, other)
    769             return self
    770 
--> 771         return np.multiply(self, other, self)
    772 
    773     def __rmul__(self, other):

/usr/lib64/python2.7/site-packages/astropy/units/quantity.pyc in __array_prepare__(self, obj, context)
    369             if not np.can_cast(result_dtype, obj.dtype):
    370                 raise TypeError("Arguments cannot be cast safely to inplace "
--> 371                                 "output with dtype={0}".format(self.dtype))
    372 
    373             result = self  # no view needed since we return the object itself

TypeError: Arguments cannot be cast safely to inplace output with dtype=>f4

**Comment by StarryNate** [comment]
OK, I think I diagnosed this one: If I convert the data and error arrays to float64, it no longer crashes. However, some of the resulting aperture_sum_err values are still 'nan', which I think is weird because I specifically masked pixels for which the error array had a value of nan...

**Comment by larrybradley** [comment]
Thanks, @StarryNate.  It looks like your data array came from a FITS file because its `dtype` is `>f4` (big-endian float32).  Some tools, especially those that use `Cython` behind the scenes, will choke on those files because of the data type (especially on little-endian machines).  When reading FITS data, I convert it to `np.float` to avoid those types of issues, as you discovered.

The issue of not masking `np.nan` in aperture photometry is an actual bug, which I fixed in #268.  It will be merged into the development master soon.  Thanks for reporting that!

**Comment by StarryNate** [comment]
Awesome! Thanks for the quick response!

Nathaniel R. Ross
UCLA

**Comment by larrybradley** [comment]
This is merged now.  Thanks again.
