### ISSUE TITLE
E   ImportError: No module named circular_overlap

### ISSUE THREAD

**Issue by SonuTabitha** [astropy/photutils#349]
I am getting this error after running the photutils test. How to fix it?

**Comment by larrybradley** [comment]
@SonuTabitha `circular_overlap` is a `Cython` module that needs to be compiled during the package build step.  It appears that your installation of `photutils` failed or possibly that you are running tests from an unbuilt source directory.  Can you please describe the detailed steps you took to install `photutils` (and which version), how you are running the tests, and if you are running the tests from the `photutils` source directory?

I also refer you to the [Photutils installation docs](http://photutils.readthedocs.org/en/latest/photutils/install.html).

**Comment by SonuTabitha** [comment]
I have python 2.7.10 installed in my system. I downloaded photutils-0.2.1.tar.gz (md5). I then ran the codes python setup.py build and python setup.py install respectively.

**Comment by larrybradley** [comment]
Since you are trying to install from a source distribution, I suspect that your `build` or `install` steps are failing.  Note that `Cython (>0.15)` is required to build `photutils` from source.

However, because you are trying to install a *released* version of `photutils (0.2.1)`, I highly recommend that you use either `pip` or `conda`, simply:

`pip install photutils`
or
`conda install -c http://conda.anaconda.org/astropy photutils`

**Comment by SonuTabitha** [comment]
I did 
`pip install photutils`
and i got the output as shown below.
![screen shot 2016-04-01 at 9 58 11 pm](https://cloud.githubusercontent.com/assets/18210111/14213323/01f62b98-f855-11e5-8641-1e1011b3c215.png)

**Comment by larrybradley** [comment]
Run `pip install photutils --upgrade`, to get fresh installations of those packages.

**Comment by SonuTabitha** [comment]
I upgraded the packages and ran the photutils test again . There were no errors this time. I got the result as "849 passed, 147 skipped in 38.12 seconds" . Is it okay?

**Comment by larrybradley** [comment]
Yes, the tests passed.  You have no failures.

**Comment by SonuTabitha** [comment]
Thanks a lot !

**Comment by jjvh91** [comment]
Hey,
I'm running into this same problem, but can't seem to figure it out. I installed photutils with pip, also trying the --upgrade you suggest in this topic. 

But still it says it cannot find circular_aperture. What could be going wrong?

**Comment by larrybradley** [comment]
@jjvh91  `circular_aperture` is a `Cython` module that needs to be compiled and that step is failing for you.

Which version of `photutils` are you trying to install?  If you are installing the latest *released* version (0.2.2), you do not need `Cython` and `pip install photutils` should work fine. A recommended alternative is to use `conda install photutils -c astropy`.

If you are trying to install a *development* version, then you need `Cython`, a C compiler suite (e.g. XCode for OSX), and the development headers for `Python` and `Numpy`.  Please see http://photutils.readthedocs.io/en/latest/photutils/install.html#installing-the-latest-development-version.

**Comment by jjvh91** [comment]
When I left the comment I was trying to install the development version -- but mostly because using the latest release version was giving me problems (well, this very problem to be precise.)

I tried it once more (using pip install photutils --user). Could the fact that I am installing it locally with --user be causing any trouble perhaps?

**Comment by larrybradley** [comment]
You could try uninstalling it completely and starting fresh.  Installing with `--user` shouldn't be causing any trouble.
