### ISSUE TITLE
How to create a gaussian psf in IDL? and how to add some background noise to it?

### ISSUE THREAD

**Issue by MiraYugario** [astropy/photutils#352]

**Comment by bsipocz** [comment]
I'm closing this as photutils is a python package and thus this issue is unrelated. I'm sorry but we can't provide any IDL helpdesk support.

Also this is an issue tracker for bugs and features for photutils, for general python / astropy / photutils questions I would suggest to write to either the astropy mailing list [0] or to the Python in Astronomy facebook group [1]. A much larger group of people are reading those forums than the developers here, thus it's more likely you get a quick answer.

[0] - http://mail.scipy.org/mailman/listinfo/astropy
[1] - https://www.facebook.com/groups/astropython/
