### ISSUE TITLE
Not able to load images using Datasets(photoutils.datasets). Kindly help

### ISSUE THREAD

**Issue by MiraYugario** [astropy/photutils#354]
I wanted to create some gaussian sources with background noise. So I used photoutils dataset `make_gaussian_sources` . I ran the code but got the following output.
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')'
It didn't generate any image. How to fix this?

**Comment by larrybradley** [comment]
@MiraYugario This is clearly **not** a `photutils` issue.  Please inspect your own error message, which clearly states that your issue is with the `matplotlib` package.  Google is very helpful for solving general problems like this.  We do not provide general help here.

I can only reiterate and emphasize what @bsipocz has already relayed to you.  Please stop posting unrelated issues here and use the appropriate forums, like stackoverflow or the Python Users in Astronomy FB group.
