### ISSUE TITLE
Implement bilinear interpolation

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#36]
At the moment, the photometry assumes nearest-neighbor interpolation. It would be nice to implement bilinear interpolation as it is flux-conserving and maybe more realistic.

**Comment by larrybradley** [comment]
I discussed this issue with @astrofrog to get more context.  The issue arose because a user had a *model* for the data, where the data values could vary *within* a pixel, instead of "real" data where data is assumed to be constant over a pixel (e.g. detectors integrate within a pixel bin).  We decided the best approach in such cases is that users should pre-interpolate their data before doing the photometry.
