### ISSUE TITLE
Update segmentation/threshold detection to OOP interface

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#389]
It just occurred to me that the updates @mirca made in #379 perhaps could also be applied to the code described in this section: https://photutils.readthedocs.io/en/latest/photutils/detection.html#source-extraction-using-image-segmentation ... Do you agree, @larrybradley ?  Or do you think this is better left as a function given that it _yields_ an object that requires more thought to operate on (and doesn't really fit in the "pipeline" style that we have thus far been using.

**Comment by mirca** [comment]
@larrybradley Thoughts here? I would be interested in tackling this.

**Comment by larrybradley** [comment]
@mirca  Thanks, but let's hold off on this.  My initial thoughts are that these are better left as functions because they are part of an interactive workflow -- one may need to do some intermediate operations on returned objects between steps (and in fact I've added tools to do so, e.g. modify a segmentation image).  As @eteq says, I don't think it really fits the "pipeline" or one-function-does-all style.  If someone wants a non-interactive "pipeline" for this, they can simply create a small script by stringing together only a few function calls.
