### ISSUE TITLE
GroupPSF class defined within the DAOPhotPSFPhotometry class

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#417]
I assume this wasn't intentional?
https://github.com/astropy/photutils/blob/master/photutils/psf/photometry.py#L403

Should `GroupPSF` belong in the `groupstars.py` module?

**Comment by mirca** [comment]
@larrybradley that was actually intentional. However, I see the usefulness of putting it in ``groupstars.py`` or even in ``models.py``. @eteq, @hamogu, @bsipocz  thoughts?

**Comment by larrybradley** [comment]
Also, it's a bit unusual to define a class within a class.  Is the `GroupPSF` class useful *only* to the `DAOPhotPSFPhotometry` class?

**Comment by eteq** [comment]
I definitely think it should *not* be a class inside a class.  Users should be able to use the grouping machinery independently of the `DAOPhotPSFPhotometry`.

@mirca, can you clarify why it's a class-inside-a-class?  Was that a functionality thing or because it's sort of logically connected to `DAOPhotPSFPhotometry`

**Comment by eteq** [comment]
Actually, looking more closely, I realized I'm not sure this is necessary at all as it stands.  Will make a PR shortly to illustrate what I'm thinking.
