### ISSUE TITLE
Implement getting of uncertanties in PSF photometry

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#443]
I see that the `get_uncertainties()` method for `DAOPhotPSFPhotometry` [currently raises](https://photutils.readthedocs.io/en/latest/_modules/photutils/psf/photometry.html#DAOPhotPSFPhotometry.get_uncertainties) a `NotImplementedError`.

What's the ETA on this?

**Comment by mirca** [comment]
I'm going to tackle this soon. Everybody needs to compute uncertainties :)

Currently, astropy fitters do not provide a standard way to compute uncertainties of the fitted parameters. For [LevMarLSQFitter](http://docs.astropy.org/en/stable/api/astropy.modeling.fitting.LevMarLSQFitter.html), one can get uncertainties through the ``fit_info`` dictionary, but this is not true for the other astropy fitters.

However, this may change with [astropy/saba](https://github.com/astropy/saba), which allows one to use astropy models into [sherpa](https://github.com/sherpa/sherpa) fitters.

cc @eteq @hamogu

**Comment by Gabriel-p** [comment]
I can not find the `get_uncertainties()` method anymore. Has this functionality been added? Does PSF photometry now also return uncertainty estimates?

**Comment by mirca** [comment]
@Gabriel-p Unfortunately, not yet.

**Comment by Gabriel-p** [comment]
I thought that, since the method was not there anymore (at least I couldn't find it?) it might have been added to the new dev version. Thank you @mirca!

**Comment by eteq** [comment]
I renamed this to be an actual issue that we can track.

Some additional details of what I think we *want* (although @mirca, @Gabriel-p or @hamogu might have other ideas): 
* For fitters that support uncertainties, the tables that output the results of PSF fitting should contain a "flux_fit_unc" or maybe "flux_unc" column, which would get the results of the fitting.
* Fitters that don't have uncertainties just leave off that column
* Down the road we *may* want it to be a bit more flexible, like letting fitters have some way to report more than just scalar uncertainties.  But I think it's probably best to deal with that later and try to just get the above in ASAP

**Comment by Gabriel-p** [comment]
Hi guys, sorry to be a bother. Just checking to see if any improvements were made on this issue. This is the only thing keeping me from using `photutils` to process publishable data, since I can't present photometry with no assigned uncertainties.

**Comment by larrybradley** [comment]
@Gabriel-p There is an open PR (#516) that will hopefully be merged soon.

**Comment by typpo** [comment]
Could someone please point me to a resource that explains what level of uncertainty is considered typical for PSF photometry, and/or how to tune the input parameters to reduce uncertainty?  My residual image looks good but `flux_fit_unc` is quite large in proportion to the overall flux and I'm looking for ways to improve it.

**Comment by hamogu** [comment]
@typpo I don't think there is a "typical" uncertainty. That depends a lot on what you are observing and what instrument you use. E.g. an object observed in an older, 1 m telescope with hardware that needs more love and software that was written by a grad-student in IDL long ago and has never been upgraded, might give you 50% error, while the same star observed with HST might have 1 % errors. But then again, if you are using HST anyway, you are probably not looking at bright stars but super ultra-faint galaxies at high redshifts - and those will be so faint that your errors are larger again.

Are your sources faint compared to the background? In that case there is not that much you can do. Do you allow many free parameters (e.g. size of the PSF variable over the field or a complext background shape)? Try reducing the number of free parameters, e.g. try a simpler background model, fix the size of the PSF if it's the same in every image, ...

 I still find the DAOPhot manual by Peter Stetson a insightful, if not easy, introduction. Ignore the software part (since you are using astropy), but read the general discussion that is interspersed.
