### ISSUE TITLE
ImportError: No module named DAOStarFinder

### ISSUE THREAD

**Issue by panossk** [astropy/photutils#445]
Hi, 

i finished installing astropy, photutils, and updating numpy and scipy.  
I started testing everything with the examples proposed in http://photutils.readthedocs.io/en/latest/photutils/getting_started.html 

Everything works until the import of DAOStarFinder which leads to the error message in the title. 
How is that even possible? 
It happens both on my laptop, and on my workplace's server which i didn't configure.

**Comment by mirca** [comment]
Hi @panossk, which version of photutils have you installed?

**Comment by panossk** [comment]
hi mirca, thanks for your attention,
 I'll check as soon as I return to my office. 
Photutils was installed using pip, shouldn't it be the most up-to-date, by definition?

**Comment by mirca** [comment]
``photutils`` version from ``pip`` is ``0.2.2``, which does not has ``DAOStarFinder``. You can look at http://photutils.readthedocs.io/en/stable/index.html for the correspondent docs.

**Comment by panossk** [comment]
oh, thanks for that info.
It's quite odd. 0.2.2 is the most recent? and doesn't have this module?

**Comment by bsipocz** [comment]
@panossk - There were quite many reorganization and many new functionality added recently that will be released soon. ``DAOStarFinder`` is one of these new addition.
However the daofind functionality is available in released versions, too, but in a different function form rather than the object oriented form. You can always access the documentation of the latest release under the name "stable": http://photutils.readthedocs.io/en/stable/photutils/getting_started.html. 

(In your link "latest" means the development version, and you can check the version number in the upper left corner in the docs, whether it is for your installed version.)

Hope it helps.

**Comment by panossk** [comment]
so basically the main thing is a naming issue? dayum.
so that means i was misdirected to that initial link in the start, as I was only looking for simple (user-oriented, not developer) examples... :/ 

Well,  I hope that that's all there is to it. I'll check it on Monday.
Thanks!

**Comment by bsipocz** [comment]
@panossk - The main issue was that you were looking at the documentation of a different version than your installed version. There are several versions of the documentation, it's always worth to check and match the versions to use the one that matched the installed package.

You're also welcome to work with the developer version to try out new things not yet available in the release, it can be installed with pip, too, instructions are here: http://photutils.readthedocs.io/en/latest/photutils/install.html#building-and-installing-using-pip

**Comment by panossk** [comment]
thanks,
I'm afraid I won't have time for that right away. 
It's just that in the aftermath of this it seems frustrating that i found myself on a developer's version instructions, when I am as much of a noob as can be.
