### ISSUE TITLE
Failing RTD builds

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#486]
Currently RTD builds are failing.  The reason is because of the "remote" Zenodo badge image on the main doc page.  Apparently the newest release of `docutils` and `Sphinx` don't get along with respect to "remote" images.  I think the solution is to (temporarily) pin `Sphinx` to an earlier version.  I won't get a chance to fix this until  the new year.  @bsipocz if you have time, perhaps you can take a look?  Thanks.

**Comment by larrybradley** [comment]
Reference:  https://github.com/sphinx-doc/sphinx/issues/3212

**Comment by bsipocz** [comment]
Sure, I'll have a look at it.
For some reason RTD already uses a rather old sphinx (1.3.5), and the 0.12 docutils but the problem indeed looks very similar to that in the sphinx issue.

**Comment by bsipocz** [comment]
The build has been fixed with a072434b12d3850aba9b81afd3ddb663d4b9549f by requiring to have at least sphinx 1.5.1. 
Limiting docutils version in the requirement file didn't have any effect, I think it wasn't downgraded from the installed 0.13.1 version. However the upstream bug has been fixed in Sphinx 1.5.1, and requiring to have 1.5.1 as a minimum version is working now.
