### ISSUE TITLE
Unit errors with calc_total_error

### ISSUE THREAD

**Issue by philastrophist** [astropy/photutils#535]
Why is the source variance calculated as the maximum of `data * data.unit / effective_gain.value`? Surely we need the unit of the effective gain as well for correct conversion?

```
from astropy import units as u
from photutils.utils import calc_total_error
import numpy as np

nmgy = u.def_unit('nanomaggy', 3.631e-6 * u.Jy)
u.add_enabled_units([nmgy])
u.__dict__['nanomaggy'] = nmgy

data = np.arange(10) * nmgy
bkg_err = np.ones_like(data.value) * u.electron
gain = 2. * u.electron / nmgy

error = calc_total_error(data, bkg_err, gain)
```

```
Traceback (most recent call last):
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity_helper.py", line 22, in get_converter
    scale = from_unit._to(to_unit)
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\core.py", line 975, in _to
    "'{0!r}' is not a scaled version of '{1!r}'".format(self, other))
astropy.units.core.UnitConversionError: 'Unit("electron2")' is not a scaled version of 'Unit("nanomaggy2")'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity_helper.py", line 283, in get_converters_and_unit
    units[fixed])
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity_helper.py", line 25, in get_converter
    from_unit, to_unit, get_current_unit_registry().equivalencies)
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\core.py", line 880, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 'electron2' and 'nanomaggy2' are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/project/test.py", line 26, in <module>
    error = calc_total_error(data, bkg_err, gain)
  File "C:\Anaconda2\envs\project\lib\site-packages\photutils\utils\errors.py", line 114, in calc_total_error
    0. * bkg_error.unit**2)
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity.py", line 386, in __array_prepare__
    converters, result_unit = UFUNC_HELPERS[function](function, *units)
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity_helper.py", line 294, in helper_twoarg_invariant
    return get_converters_and_unit(f, unit1, unit2)
  File "C:\Anaconda2\envs\project\lib\site-packages\astropy\units\quantity_helper.py", line 288, in get_converters_and_unit
    .format(f.__name__))
astropy.units.core.UnitConversionError: Can only apply 'maximum' function to quantities with compatible dimensions
```

**Comment by larrybradley** [comment]
@philastrophist The calculation in `calc_total_errors` assumes that `data` and `bkg_error` have the same units.  This is required to do the addition with `Quantity` objects and to ensure the output total `error` array has the same units as the input `data`.  Sorry that wasn't documented or checked within the code.  I submitted a fix in #537 to explicitly require this and document it.

For your specific example, you effectively need to calculate `error = np.sqrt(data * gain + bkg_err**2)`.  However, this will fail with your `Quantity` inputs because the first term has units of `u.electron`, but the second term has units of `u.electron**2`.  For calculating the Poisson variance, the `u.electron` units should be treated essentially as dimensionless (counts).  The `calc_total_errors` functions handles this by assuming ``data`` and ``bkg_error`` have the same units.  For your specific example, you can either strip the units (having ensured the equation works for your units), use the above equation, and then add the units back in, or do this:

```python
>>> source_variance = (data * gain).to("electron2", equivalencies=[(u.Unit("electron"), u.Unit("electron2"))])
>>> error = np.sqrt(source_variance + bkg_err**2)
```

which will give `error` in units of `u.electron`.

**Comment by virajpandya** [comment]
Building on this question, I noticed that `calc_total_erors` *divides* `data` by the `effective_gain`. Since `effective_gain` is assumed to have units of electrons/image_units, wouldn't you want to *multiply* `data` by ``effective_gain`? Basically I think `calc_total_errors` isn't actually doing the calculation that @larrybradley said in the message above: `error = np.sqrt(data * gain + bkg_err**2)`. Instead it's doing `error = np.sqrt(data / gain + bkg_err**2)`!

**Comment by larrybradley** [comment]
@virajpandya It is doing the correct calculation.  `calc_total_error` requires the `data` and `bkg_error` inputs to have the same units (as described above) and the output is also returned in the same units, **not** electrons.


This is the total error in *electrons* (assuming `data` and `bkg_error` have the same units):
The first term is the image Poisson statistics, which require the actual counts (e.g. electrons).

```
error_total [e-] =  np.sqrt((data * gain) + (bkg_error * gain)**2)
```

But we want to convert this result from electrons back to the native `data` and `bkg_error` units.  To do this we need to divide by the gain (electrons/ image_units):

```
error_total [image_units] = error_total [e-] / gain [e-/image_units]
```
giving:

```
error_total [image_units] = np.sqrt(data / gain + bkg_error**2)
```

This is what `calc_total_error` is correctly returning.
