### ISSUE TITLE
Background2D "exclude_mesh_method" does not seem to work

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#543]
As in the following code, I made a fake image.

As far as I understand, the `bkg1` and `bkg2` must give different results in the following case, since `exclude_mesh_method` differs a lot. At least at the central mesh, `mesh_nmasked` gives 144, so I thought that mesh is neglected for background estimation in `bkg2`. But the figure I drew, the ratio between the two backgrounds, is a constant map of value 1.0. 

```python
from photutils import Background2D, SigmaClip, SExtractorBackground
from astropy.modeling.functional_models import Gaussian2D
from matplotlib import pyplot as plt
import numpy as np
#%%
FWHM=2.5
np.random.seed(1)
rand = 10*np.random.rand(100,100) + np.random.normal(loc=50, scale=10, size=(100,100))
xx, yy = np.mgrid[:100,:100]
img = rand + Gaussian2D.evaluate(xx, yy,
                                  amplitude=3000, theta=0,
                                  x_mean=50, y_mean=50,
                                  x_stddev=3, y_stddev=3)
img = img.astype(int)

box = np.array((20, 20)).astype(int)
filt = np.array((2*FWHM, 2*FWHM)).astype(int)
sigma_clip = SigmaClip(sigma=3., iters=10)

bkg1= Background2D(img, 
                  box_size=box, 
                  filter_size=filt,
                  sigma_clip=sigma_clip, 
                  exclude_mesh_method='threshold',
                  exclude_mesh_percentile=99,
                  bkg_estimator=SExtractorBackground())
bkg2= Background2D(img, 
                  box_size=box, 
                  filter_size=filt,
                  sigma_clip=sigma_clip, 
                  exclude_mesh_method='threshold',
                  exclude_mesh_percentile=1,
                  bkg_estimator=SExtractorBackground())

plt.imshow(bkg1.background/bkg2.background)
print(bkg.mesh_nmasked)

```

Am I misunderstanding the SExtractor background estimation?

**Comment by larrybradley** [comment]
@ysBach, thanks for your report.  In your examples, changing `exclude_mesh_percentile` indeed has no effect because the mesh rejection applies only to pixels in the input `mask` array, not any additional masked pixels resulting from sigma clipping.  This is stated in the documentation for the `exclude_mesh_method` keyword.

I just submitted a PR (#544) that will change this behavior to also include the sigma-clipped pixels in the mesh rejection algorithm.  Also note that the two `exclude_mesh_*` keywords were combined into a single keyword called `exclude_percentile`.
