### ISSUE TITLE
Photometry notebooks are outdated

### ISSUE THREAD

**Issue by saimn** [astropy/photutils#557]
The PSF Photometry [notebooks](http://photutils.readthedocs.io/en/stable/photutils/psf.html#example-notebooks-online) "PSF photometry on artificial Gaussian stars" and "PSF/PRF Photometry on Spitzer Data" use a `psf_photometry` function that has apparently been removed. Maybe better to remove these notebooks, because it's quite frustrating to read the notebooks and find that it's not possible to do the photometry that way.

**Comment by pllim** [comment]
Oh yeah, I just encountered this and got really excited and then really confused.

**Comment by bsipocz** [comment]
Yeah, I suppose you've found the reason for the big red warning about the API 😉 

The notebooks were more like proof of concepts and API snapshots at the time of the photutils+psf GSoC projects rather than part of the tested documentation and stabilised API. 

Given this history, I would totally be on the side of removing them.
