### ISSUE TITLE
should `Background2D` yield a unit-ful background?

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#696]
The title is suggestive since of course I think the answer is "yes" :wink: ... But I noticed the following:

```
>>> from astropy import nddata
>>> from photutils import Background2D
>>> d = nddata.CCDData(np.random.randn(100, 100), unit=u.ct/u.s)
>>> bkg = photutils.Background2D(d, 3)
>>> bkg.background
array([[... ]])
```

wouldn't it be more natural in that case for the background to have units of `ct/s`?  This is desirable because then it can be passed directly into ``d.subtract(bkg.background)``.

An alternative, if doing this is "too API-breaking", might be to have `qbackground`.  But then everything else in `Background2D` should get a q-something.  I'm tempted to instead just bite the bullet and say "if you don't want units you have to pass in something without units".

ccc @larrybradley

**Comment by Yash-10** [comment]
Hello, I would like to work on and think more about this.

In principle, not specifying the `unit` argument inside `CCDData` would raise a `ValueError`. So as you have said, we would have to release the restriction on CCData of specifying the `unit` argument so that we would be able to subtract `bkg.background` from `d` without any unit conversion errors. The situation seems a little tricky since, as you have mentioned, the corresponding changes might be API breaking.

Please let me know your thoughts on this and if this is what we are looking for.

Alternatively, to set units for `bkg.background` we might consider converting the original background (a numpy array) to NDData type (so that it's units can be set) and maybe leave the optional arguments as default, as below.

```py
d = nddata.CCDData(np.random.randn(100, 100), unit=u.ct/u.s)
bkg = photutils.Background2D(d, 3)
bkg.background = NDData(bkg.background, unit=u.ct/u.s)
subtracted = d.subtract(bkg.background) # can be done without any unit conversion errors
```

Thank you.

**Comment by Yash-10** [comment]
> I'm tempted to instead just bite the bullet and say "if you don't want units you have to pass in something without units".

@eteq Does the change needs to be made for CCDData (to release the restriction of specifying a `unit` argument so that `d` can be unitless) or in `photutils.Background2D` to optionally have a `unit` argument? In the second case - if an `unit` argument is given, then the `background` will have the corresponding passed in units else it will not have any units. Does the second option seems more favourable?

Thanks!

**Comment by larrybradley** [comment]
@eteq @Yash-10 I've put in a PR to allow `Quantity`, `NDData`, and `CCDData` inputs to `Background2D` that will also handle units:  https://github.com/astropy/photutils/pull/1140
