### ISSUE TITLE
Definitions of alpha and gamma in Moffat functions

### ISSUE THREAD

**Issue by rjavila** [astropy/photutils#706]
The documentation in the Moffat1D and Moffat2D models use alpha and gamma, but as far as I can tell, everywhere else these two parameters are defined as beta and alpha, respectively. For example equation 1 in this paper https://arxiv.org/pdf/astro-ph/0109067.pdf

Can we change the code and documentation to reflect this? It has confused me bit while using the models. Thanks.

**Comment by bsipocz** [comment]
The Moffat models are not defined in photutils, but in astropy. The documentation clearly states what each parameters mean, as well as provides the equations. 

I guess it's very unlikely to go through a deprecation cycle to rename one of them, but either way the issue should be raised in the main astropy repo rather than here.

**Comment by rjavila** [comment]
Sorry, I was using both packages on something and got things confused. I shouldn't open issues late at night.

**Comment by bsipocz** [comment]
No worries.
