### ISSUE TITLE
Input Issue Resulting in Infinite Loop

### ISSUE THREAD

**Issue by HSouch** [astropy/photutils#707]
On extremely rare occasions, (3 in ~16000 iterations for my own work), the fitting routine in photutils.isophote.fitter results in an infinite loop. My own code that uses the fitting routine is below.
```
flux = Ellipse(data)  # Where data is a valid numpy ndarray with no nan or inf pixels

try:
    fitting_list = flux.fit_image()
except IndexError:
    fitting_list = []
...
```

When this infinite loop occurs, it continuously logs the following:
```
INFO: Improper input: N=5 must not exceed M=0 [photutils.isophote.fitter]
INFO: Improper input: N=5 must not exceed M=0 [photutils.isophote.fitter]
...
```
which appears to be a result of the code on lines 151-155. Perhaps changing the way this exception is handled to a warning would be a better alternative?

**Comment by larrybradley** [comment]
CC: @ibusko

**Comment by shivangeerathi** [comment]
Hi, 
I am having the same issue with the latest version of photutils (v0.7.2) on a 64-bit machine with Ubuntu 18.04 LTS. It occurs rather randomly. 
Does anyone knows a fix to this ?

**Comment by ibusko** [comment]
@HSouch @shivangeerathi  could you please provide us with a sample image were the issue manifests itself?

**Comment by shivangeerathi** [comment]
@ibusko 
[Here](https://we.tl/t-b1Aicw29X9) is one of the cases where the error occurs.

**Comment by ibusko** [comment]
@shivangeerathi I can't make it go into an infinite loop. Instead, it fails at the very beginning with a stop code of -1. Running under a debugger, I can see that this is caused by a positive intensity radial gradient condition. This gradient must be always negative for the algorithm to work (intensity decreases as the radius increases). The cause in this particular image seems to be one (or two) star images that are superimposed on the galaxy image. The mask file you sent me doesn't seem to mask out these two particular star images.

That said, you probably have found a combination of input parameters that makes the algorithm successfully go over this specific hurdle. And then it will go into the loop. What is the specific set of parameter values you use?

**Comment by shivangeerathi** [comment]
This is the input geometry that I had used: 
`x0 = 1000, y0 = 1000,  sma = 50,  eps = 0.3,  pa = 135*np.pi/180`
In addition, I had initially restricted the maxsma to 670 px.

**Comment by ibusko** [comment]
@shivangeerathi sorry for the long delay in answering this. I tried to reproduce your problem but couldn't. I am using this script to drive the test case with your parameters:

from ..ellipse import Ellipse
from astropy.io import fits
from astropy.utils.data import download_file

url = 'file:/path_to_filerF31D196_final.fits'
path = download_file(url)
hdu = fits.open(path)
data = hdu[0].data
hdu.close()

geometry = EllipseGeometry(1000., 1000., 50., 0.3, 135 * np.pi / 180)
ellipse = Ellipse(data, geometry=geometry)
iso_list = ellipse.fit_image(maxsma=670)
print(iso_list)

I get a seemingly reasonable solution with this. I tried to change the parameters around the values you provided to see if that would trigger something, but to no avail. It always runs to completion.

Did you ever managed to get a fit on this same image, with different parameter values?
