### ISSUE TITLE
PSF photometry hangs, may be bug

### ISSUE THREAD

**Issue by Vb2341** [astropy/photutils#737]
BasicPSFPhotometry has issues running on large numbers of stars (11000), which is expected, due to the large amount of fitting that has to be done.  However, the length of time doesn't seem consistent, sometimes it executes in a few minutes, and sometimes it hangs for 20+ minutes.  There might be a memory issue, or something else, but it might be worth investigating.

**Comment by saimn** [comment]
I guess that this is the same as https://github.com/astropy/astropy/issues/8338, which is fixed by https://github.com/astropy/astropy/pull/8349

**Comment by larrybradley** [comment]
The PSF photometry tools have been rewritten and should no longer have this issue.  However, memory allocation is an issue when using source grouping with very large group sizes (https://github.com/astropy/photutils/issues/1808).  That is a memory issue with compound models that needs to be fixed in Astropy.
