### ISSUE TITLE
How do I estimate the uncertainities on a Background2D?

### ISSUE THREAD

**Issue by rhandberg** [astropy/photutils#799]
Short question: How can I get and estimate of the uncertainties on the estimated background coming out of Background2D?

I am doing the following steps:
1. I have CCD image with a corresponding "uncertainty image" ($\sigma_{img}$; the errors on each pixel in the image).
2. I pass the image through Background2D to give me an estimate of the background.
3. I subtract the estimated background from the original image.

I now want to propagate the uncertainties through this process.
In math, this would be something like:
$\sigma_{new image} = \sqrt{\sigma_{img}^2 - \sigma_{bkg}^2}}$

But the question is, how do I get $\sigma_{bkg}$ from Background2D?

**Comment by ysBach** [comment]
If you've used Background2D, e.g., ``bkg`` is a ``Background2D`` object, 
you can use ``bkg_rms = bkg.background_rms`` ([doc](https://photutils.readthedocs.io/en/stable/api/photutils.background.Background2D.html#photutils.background.Background2D)).

**Comment by rhandberg** [comment]
@ysBach - That does not use the known uncertainties on the input image. Doing that would, as far as I understand, just estimate the scatter in the background-subtracted image, and not take the uncertainties in the original image into account. Or have I misunderstood the documentation?

**Comment by larrybradley** [comment]
@rhandberg The `background_rms` 2D array is a measure of the noise in the input image.  By default, it calculates the standard deviation (`bkgrms_estimator` = `StdBackgroundRMS`) of the input data within each of the defined background meshes and then interpolates the std. values in the meshes (the low-resolution image) to the full-sized image.  It's exactly analogous to how the `background` 2D array is calculated, except `background` uses a different statistical estimator (e.g. mean, median, or mode instead of std) than `background_rms` calculates in each of the meshes.
