### ISSUE TITLE
Separate sky estimation for each stars in IterativelySubtractedPSFPhotometry

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#850]
Currently the PSF photometry in photutils accepts the sky estimator as `bkg_estimator`. 
But in PSF photometry process, as far as I understand, we have to subtract the sky from regional circular annulus estimation, rather than SEx background estimator, to get the PSF (e.g., Stetson 1987 PASP). 
I tried to do something like
```python
# data: sky not subtracted
stars = extract_stars(NDData(data), star_table, size=fwhm*4+1)
for i, s in enumerate(stars):
    s._data -= pick[i]["background"]
```
but this modifies the original data frame. 

Is there a simple way to make the code do the background estimation using the circular annulus near the object?

**Comment by pjpessi** [comment]
Hi, is there any new information about this issue?
I am currently using BasicPSFPhotometry and I am trying to subtract the sky from a regional circular annulus as described here.
To do this I would also like to know how to specify a circular area in which to fit the PSF model. My understanding is that fitshape controls the area where the PSF is fitted but fitshape only allows rectangular areas and not circular ones. Do you know what I am missing in order to fit the PSF model to a circular region?

**Comment by larrybradley** [comment]
@ysBach There is a relatively new `LocalBackground` class (https://photutils.readthedocs.io/en/latest/api/photutils.background.LocalBackground.html) that can compute a local background using a circular annulus aperture.

@pjpessi There is no current way to fit the PSF in a circular region.  However, it is strongly recommended that you use a `fit_shape` parameter that covers only a few pixels (e.g., 5x5, or 3x3) where the PSF has the highest SNR.
