### ISSUE TITLE
X and Y centroid is wrong in new versions of anaconda

### ISSUE THREAD

**Issue by gregjaffry** [astropy/photutils#862]
I recently updated my code base from anaconda 2.4.1 to Anaconda 5.3.1, both were running with photutils 0.4 since 2.7 is not supported in the latest versions.

The error I am seeing between my two builds is that the old build had the correct x and y centroids, and the new build has the wrong centroids even though it is segmenting the sources correctly. I am running the exact same script in both builds and I am seeing these two different outputs. Please see the screenshots below.

Old version (works great)
![old_version](https://user-images.githubusercontent.com/36544141/59124202-14fa6a80-892d-11e9-9341-7734a6c74246.png)

![old_plots](https://user-images.githubusercontent.com/36544141/59124213-1af04b80-892d-11e9-81f5-c43bae096461.png)

new version (centroids the image properly, but reports the wrong x,y centroids)
![new_version](https://user-images.githubusercontent.com/36544141/59124352-673b8b80-892d-11e9-9430-68bf31c7d839.png)

I have been banging my head against a wall on this for two days, so any help would be great.

**Comment by larrybradley** [comment]
@gregjaffry This is due to a breaking change in `scikit-image 0.14` (specifically they changed the (x, y) order in their moments function).  Soon after this breaking change I removed the `scikit-image` dependency on image moments in `photutils`.

If you revert to scikit-image 0.13.1, it should give the expected results.

Also, python 2 will no longer be supported (end of life) by the Python Software Foundation starting Jan 1, 2020 (https://www.python.org/dev/peps/pep-0373/), so you should consider upgrading soon.

**Comment by gregjaffry** [comment]
THANK YOU!!!! it works great now.
