### ISSUE TITLE
disallowing all zero SegmentationImage seems prohibitively restrictive

### ISSUE THREAD

**Issue by astromancer** [astropy/photutils#901]
I've been happily inheriting from `SegmentationImage` for some time now [here](https://github.com/astromancer/obstools/blob/c54cdb6aff4eea34c1c5ee247bdf9eee68c256c3/phot/segmentation.py#L861) (this code is in development for a new pipeline for the SALTICAM  instrument of SALT as part of my Phd). However, [this](https://github.com/astropy/photutils/commit/a845d83cbbc36d9236d8b2060bb3f1ed96b04386#diff-00e7811220b26f668b507adf3d53f191) recent update broke some functionality of my code, specifically the ability to initialize this class with an all zero array.  I feel it's useful to be able to do so and that disallowing this is too restrictive:  My use case is one where I initially create the empty segmentation image and subsequently add labels to it for detections of progressively fainter objects: [example here](https://github.com/astromancer/obstools/blob/c54cdb6aff4eea34c1c5ee247bdf9eee68c256c3/phot/segmentation.py#L136)
Is there a specific reason why all zero `SegmentationImage` is now being disallowed? Seems like this bit of code slipped in with the test for other "obviously wrong" inf / nan values.

**Comment by astromancer** [comment]
#836

**Comment by larrybradley** [comment]
@astromancer A check was added disallowing an all-zero `SegmentationImage` because in that case the `SegmentationImage` does not work properly -- several of its attributes and methods raise errors because an all-zero image was never intended.  For example this could happen in an automated pipeline where no sources were detected, resulting in an all-zero segmentation images, and thus downstream attributes/methods would raise errors with no obvious reason.  Now the code explicitly raises a `NoDetectionsWarning`.

Also note that subclassing `SegmentationImage` did not work properly prior to https://github.com/astropy/photutils/pull/916 if the subclass did not manage reseting cached properties.  `SegmentationImage` caches properties and those caches would not be be properly reset in subclasses if the internal data changed.  That was fixed in version 0.7.
