### ISSUE TITLE
EPSF gets worse at each iteration

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#969]
I am trying to build an EPSF with the ``EPSFBuilder`` class - however I've found that at each iteration the EPSF actually gets worse and worse:

![Screenshot from 2019-10-18 12-49-01](https://user-images.githubusercontent.com/314716/67091897-c8118500-f1a5-11e9-8973-18b8fec4e50f.png)

Here is the full notebook:

https://gist.github.com/astrofrog/7b2c3a8c462547ffe9367f6ab28131ed

Could this indicate a bug in the EPSF building, or is the algorithm inherently unstable?

This occurs with the latest stable version (0.7.1) as well as 0.8.dev0

**Comment by astrofrog** [comment]
Ah it works nicely with photutils v0.6, so presumably this is some kind of regression?

![Screenshot from 2019-10-18 13-08-22](https://user-images.githubusercontent.com/314716/67092934-6e5e8a00-f1a8-11e9-8548-68ac6c9262be.png)

**Comment by Onoddil** [comment]
Yeah there's a bunch of issues raised with this (cf. #951 and #960) and I've got a fix ready to submit a PR for :). Thanks for the issue -- would you be able to re-run a bunch of stuff on a new dev 0.8 (or 0.7.1, whatever it ends up in)?

**Comment by emirkmo** [comment]
This was not resolved by #974 for me. I still get a diverging ESPF in 0.72 following the above code. A downgrade to v0.6x still works correctly (although Astropy also needs to be pinned to <4.0). 

Let me know if an example notebook/data would help.

**Comment by larrybradley** [comment]
Thanks, @emirkmo.  An example notebook/data would be a big help.

**Comment by larrybradley** [comment]
@emirkmo Would it be possible for you to provide an example notebook/data showing the issue?  Thanks!

**Comment by emirkmo** [comment]
@larrybradley and @Onoddil Sorry for the huge delay in responding...

I've put up an example dateset and a notebook that demonstrates that this issue still exists in photutils v1.0.1

https://github.com/emirkmo/photutils_diverging_epsf

Let me know if I should open a new issue instead.

**Comment by larrybradley** [comment]
@emirkmo, many thanks!  I'll take a look soon.

**Comment by emirkmo** [comment]
So I have done a bit more testing, and the issue is more complicated than it seems. The diverging behavior is different than what I was finding in v0.7. This seems to be an issue with the edges specifically. Re-scaling the image (vmin=-0.001,vmax=0.04) gives a better view. Increase max iterations to 500 to see the full effect (this is what we usually use with the v0.6 algorithm). I've pushed some changes to the notebook to highlight this.

**Comment by Onoddil** [comment]
I think I've managed to diff the files between the commit before my _original_ (and unfortunately ill-fated) fix for the normalisation issue was implemented in #817, and it seems that the "new" (i.e., old, Anderson & King 2000) centroiding function (`centroid_epsf`) I implemented following AK00's prescription is still the default PSF-recentering option. However, prior to that `centroid_com` was the default function used; everything else seems to roughly check out from a quick scan of the diffs, and the previous issues with the normalisation I accidentally introduced by half-combining two algorithmic implementations seem to have been correctly removed in the follow-up #974 PR. Given that the changes to the other parts of the algorithm followed improvements made by Anderson since the original paper, it probably stands to reason that the better centroiding algorithm would be the newer one.

Could you therefore add `recentering_func=centroid_com` as an option to `EPSFBuilder` and check the results again please @emirkmo? I am _hopeful_ that that's the problem, but if you still have issues we/I will have to dig into the tests a bit more. If that's the fix, then the obvious answer is to simply swap the default input recentering function back and leave `centroid_epsf` as legacy option, or remove it from the codebase again if it's going to cause users issues if they stumble upon it.

**Comment by emirkmo** [comment]
Hey, @Onoddil, great job, that definitely works! It's clearly a centroiding issue. See the updated notebook. No issues with divergence up to 500 iterations.

**Comment by Onoddil** [comment]
Perfect, thanks for confirming. I swear we had discussions back during #974 to put the original recentering back in, but I guess we never did. Guess I'll just up a quick PR to fix that now for @larrybradley's approval later

**Comment by emirkmo** [comment]
I think this solves a bunch of open issues (I was browsing them to see if I can find a solution). Thanks again for looking into so quickly and sorry it took me so long to give an example. I admit I just kept the version fixed and moved on..

**Comment by larrybradley** [comment]
@emirko, thanks again for your help and thanks @Onoddil for a quick PR.  This is fixed in #1144 and will appear in version 1.0.2 (which will like be released within a week).
