### ISSUE TITLE
Warning about unsuccessful fit

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#972]
When doing PSF photometry, I sometimes get warnings about the fit being unsuccessful:

![Screenshot from 2019-10-18 13-22-35](https://user-images.githubusercontent.com/314716/67093886-7d463c00-f1aa-11e9-957e-ff4c85bebc4c.png)

However the warning is unhelpful, since it's not clear where to access ``fit_info``.

**Comment by Onoddil** [comment]
As I recall users don't actually get access to `fit_info`, do they? If I'm remembering right, this should come out of the `self.fitter` call in `nstars`, at which point we get [this](https://github.com/astropy/astropy/blob/d77c339b553dabe16f2540741f3c94c8e54eca83/astropy/modeling/fitting.py#L890) warning raised, but then don't allow the user access to `self.fitter.fit_info` in any obvious way.

The obvious, if slightly over-correcting, answer is to suppress the warning, since it relates to things outside of the scope of the user's access... Or is there a way to overwrite the warning (unlikely) to better tell the user to check the fitter they passed into the function. Does the `fit_info` attribute of the input fitter keep the `fit_info` attribute? That doesn't exactly help if they've not passed one and get the `LevMarLSQFitter` by default and thus can't access the thing at all, but is at least something that could be done. Can't think of any solution that solves all cases except suppressing the warning at the moment though.

**Comment by marcusthomas11** [comment]
Quick bump. Has anything changed related to this as of 1.1.0? I'm very curious if I should be concerned with my fits.

**Comment by larrybradley** [comment]
Nothing has changed in version 1.1.0 to address this.  The best test would be to look at the residual image to see if the fits failed.

**Comment by larrybradley** [comment]
With the PSF photometry tools, a "flags" column was added indicating certain error conditions and access to the `fit_info` for each model fit is available in the `fit_results` dictionary.
